name: deploy-container

on:
  push:
<<<<<<< HEAD
    branches:
      - master
    paths:
      - 'packages/container/**'
=======
    - master
  paths:
    - 'packages/container/**'
>>>>>>> Add container actions

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
<<<<<<< HEAD
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}
=======
          PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
>>>>>>> Add container actions

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
<<<<<<< HEAD
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
=======
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
>>>>>>> Add container actions
